name: Build -> Push -> Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Java JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build Jar
      run: | 
        chmod +x ./mvnw 
        ./mvnw clean package
      
      
